import type { Metadata } from 'next';
import './globals.css';
import { GlobalWrapper } from '@/src/lib/GlobalWrapper';
import { Header } from '@/src/smartComponents/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// TODO: Add font Roboto
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='antialiased'>
        <GlobalWrapper>
          {/* TODO: min-h-[2000px] - for test reason. Remove in the end */}
          <div className='bg-color1 flex flex-col min-h-[100dvh]'>
            <Header />
            <div className='py-[20px] flex grow flex-col gap-[39px] max-w-[2089px] mx-auto px-[24px] w-full'>
              {children}
            </div>
          </div>
        </GlobalWrapper>
      </body>
    </html>
  );
}
